const categories = ['Excel & Dados','Contabilidade','Fiscalidade','Recursos Humanos','Gestão','Marketing','Vendas','Finanças','Power BI','Tecnologia','Administração','Empreendedorismo'];
const skills = [
  ['Excel para Gestão Financeira','Finanças','Intermédio','6 semanas','1 500 MT'],
  ['Processamento de Salários','Recursos Humanos','Prático','4 semanas','1 200 MT'],
  ['Contabilidade para Pequenas Empresas','Contabilidade','Fundamentos','5 semanas','1 300 MT'],
  ['Power BI para Decisão','Excel & Dados','Intermédio','6 semanas','1 800 MT'],
  ['Gestão Fiscal na Prática','Fiscalidade','Prático','4 semanas','1 500 MT'],
  ['Marketing Digital para Negócios','Marketing','Intermédio','5 semanas','1 400 MT']
];

export default function Home(){return <>
  <header className="nav"><div className="container nav-inner"><a className="brand" href="#"><span>Skill</span>Hub <small>by ALINVEST</small></a><nav className="nav-links"><a href="#skills">Skills</a><a href="#como-funciona">Como funciona</a><a href="#empresas">Para empresas</a><a href="#sobre">Sobre</a></nav><div className="nav-actions"><a className="btn btn-ghost" href="/login">Entrar</a><a className="btn btn-primary" href="/signup">Começar</a></div></div></header>
  <main>
    <section className="hero"><div className="container hero-grid"><div><div className="eyebrow">Aprender · Praticar · Demonstrar</div><h1>Competências que se provam na prática.</h1><p>Aprenda skills profissionais com exercícios reais, orientação de mentores e certificação verificável. Desenvolva competências que pode demonstrar no trabalho.</p><div className="hero-actions"><a className="btn btn-primary" href="/skills">Explorar skills</a><a className="btn btn-ghost" href="#como-funciona">Como funciona</a></div></div><div className="hero-card"><div className="eyebrow" style={{color:'#1769FF'}}>EXPERIÊNCIA SKILLHUB</div><h3 style={{fontSize:24,margin:'0 0 22px'}}>O seu percurso começa aqui.</h3><div className="mini-row"><span>Excel para Gestão Financeira</span><span className="badge">Em curso</span></div><div style={{padding:'18px 0 8px',fontSize:12,color:'#667085'}}>PROGRESSO · 72%</div><div className="progress"><span/></div><div className="mini-row"><span>Exercício prático</span><strong>8/10</strong></div><div className="mini-row"><span>Certificação</span><span className="badge">Em progresso</span></div></div></div></section>
    <section className="section" id="como-funciona"><div className="container"><div className="section-head"><div><div className="eyebrow" style={{color:'#1769FF'}}>COMO FUNCIONA</div><h2>Aprenda fazendo.</h2><p className="section-intro">O SkillHub foi pensado para transformar formação em capacidade demonstrável — não apenas em horas assistidas.</p></div></div><div className="grid-4">{[['01','Escolha uma skill','Encontre competências alinhadas ao seu trabalho e aos seus objetivos.'],['02','Aprenda com orientação','Conteúdo estruturado e acompanhamento de mentores profissionais.'],['03','Resolva exercícios reais','Aplique o que aprendeu em desafios práticos e receba feedback.'],['04','Construa o seu perfil','Conquiste certificações verificáveis e demonstre o que sabe fazer.']].map(([n,t,d])=><div className="card" key={n}><div className="icon">{n}</div><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
    <section className="section skills" id="skills"><div className="container"><div className="section-head"><div><div className="eyebrow" style={{color:'#1769FF'}}>CATÁLOGO DE SKILLS</div><h2>Competências para o mundo profissional.</h2><p className="section-intro">Formação prática em áreas que fazem parte do dia a dia das empresas.</p></div><a className="btn btn-ghost" href="/skills">Ver catálogo</a></div><div className="skill-grid">{skills.map(([title,cat,level,duration,price])=><article className="skill-card" key={title}><div className="skill-top"><span className="badge">{cat}</span></div><div className="skill-body"><h3>{title}</h3><div className="skill-meta"><span>{level}</span><span>·</span><span>{duration}</span><span>·</span><span>{price}</span></div><a className="btn btn-dark" href="/skills">Ver skill</a></div></article>)}</div></div></section>
    <section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow" style={{color:'#1769FF'}}>ÁREAS DE APRENDIZAGEM</div><h2>Explore por competência.</h2></div></div><div className="grid-4">{categories.map((c,i)=><a className="card" href="/skills" key={c}><div className="icon">{String(i+1).padStart(2,'0')}</div><h3>{c}</h3><p>Skills práticas e exercícios aplicados.</p></a>)}</div></div></section>
    <section className="section" id="empresas"><div className="container"><div className="cta"><div><h2>Talento que pode ser demonstrado.</h2><p>Empresas podem criar desafios, descobrir competências e conhecer participantes através do seu trabalho prático.</p></div><a className="btn btn-ghost" href="/empresa">Conhecer solução para empresas</a></div></div></section>
  </main>
  <footer className="footer" id="sobre"><div className="container footer-inner"><div><div className="brand"><span>Skill</span>Hub <small>by ALINVEST</small></div><p>Formação prática de competências profissionais em Moçambique.</p></div><small>© 2026 ALINVEST · SkillHub</small></div></footer>
</>}
